run:
	python ClockState.py
	python Clock.py
	python RoomState.py
	python Room.py
	python VacuumCleanerRobotState.py
	python VacuumCleanerRobot.py
	python VacuumCleanerRobotProblemState.py


clean:
	find . -name '*.pyc' -exec rm -v {} \;

c:
	find . -name '*.pyc' -exec rm -v {} \;

